### ISSUE TITLE
[Theora] NEON support

### ISSUE THREAD

**Issue by flibitijibibo** [FNA-XNA/Theorafile#3]
This one's mostly for @0x0ade.

In the new statically linked Theorafile, we're using Theora version 1.1.1, the most recent stable release. However, the latest Git revision has some ARM32 optimizations inside, not sure if it's usable on AArch64 though:

https://github.com/xiph/theora/tree/master/lib/arm

For whatever reason they have not done a minor point release in 10 years (!) and it doesn't seem like they're going to do it ever, so it seems we'll have to integrate the ARM changes ourselves (which we can do now that we have our own copy of the source). If it's anything like the FAudio optimizations, this should be a HUGE performance boost for ARM devices.

**Comment by flibitijibibo** [comment]
The code is in, just need to wedge it into the Xcode project.

**Comment by linnaea** [comment]
ARM64 changed the NEON/ASIMD register layout and naming so the ASM code for v7 wouldn't be usable.

I ported some of the heavier encoding funtion to use NEON intrinsics in C, which should be usable on both v7 and A64. You can find them [here](https://github.com/linnaea/theora/tree/master/lib/arm-intrinsics). It should be easier to integrate than assembly.

My own testing on Linux with AmLogic S905X3 and GCC 7.5 showed encoding speed of a 1360x768 4:2:2 source increase from 3fps to 6fps with just the 3 SATD functions ported.

I don't have a M1 Mac or Qualcomm Surface so I haven't tested on Windows or Mac.

Judging from the profiler report I don't think there's much room for improvement other than making libtheora itself multi-threaded, which would be a huge undertaking.

**Comment by flibitijibibo** [comment]
Makes sense to me - I wonder if upstream is still around to take something like this in?

Not sure when I'll get to play with this but it's definitely something I'd like to have in Theorafile, thanks for the heads up!

**Comment by linnaea** [comment]
Upstream is probably not going to take this. Their focus has shifted to Daala around 2014 which has since been developed into AV1.

**Comment by flibitijibibo** [comment]
Might be worth filing a PR just for visibility - would also be easier for third parties like us to integrate since we can add the URL to our [lib README](https://github.com/FNA-XNA/Theorafile/tree/master/lib).

**Comment by flibitijibibo** [comment]
Self-assigning this. Since the above intrinsics works applies cleanly to upstream and we recently bumped to upstream, I'll just go ahead and update to that source and test on the Switch compiler. Long as Switch is still happy, I'm happy!

**Comment by flibitijibibo** [comment]
Intrinsics work has been imported:

https://github.com/FNA-XNA/Theorafile/commit/69e0a48090f2569aff5dc5bfdbe6b02badc89d0b

Once I get the Switch project files updated this is good to go.

**Comment by flibitijibibo** [comment]
NX project files are updated (privately of course), forgot about Xcode though - will wait on that before closing.

**Comment by flibitijibibo** [comment]
Latest commit has the Xcode updates!

**Comment by flibitijibibo** [comment]
Reopening for juuust a moment. @linnaea, we may have found a visual bug caused by the arm-intrinsics, hoping to have a sample video to share soon. (CC @kiddkaffeine)

**Comment by kiddkaffeine** [comment]
Hey @linnaea, so I tested a number of game videos.  This does not appear on all, but some get some odd artifacts when NEON is enabled.  I'm not sure what distinguishes them.

Here's a sample, uploaded to Google Drive as these seem to be too large to host here:

https://drive.google.com/file/d/1LUJ-VZtrTsyH7tAgfol-y4Mb9rfVe47M/view?usp=sharing
[AN000_screenshot.zip](https://github.com/FNA-XNA/Theorafile/files/10564402/AN000_screenshot.zip)

Notice in this screenshot, there are some odd squares thoughout this frame of the video.

**Comment by linnaea** [comment]
Looks like I swapped two shift instructions in loop filter, will submit a pull request

**Comment by flibitijibibo** [comment]
This is merged, thanks for the quick fix! Will continue reporting if we see anything else.
