### ISSUE TITLE
Subtitles support?

### ISSUE THREAD

**Issue by Krakean** [FNA-XNA/Theorafile#6]
@flibitijibibo 
Hello
Is Theorafile support subtitles (.SRT at least) either as external files or those that bundled into .ogv container?

**Comment by flibitijibibo** [comment]
It does not. Theorafile just pulls decompressed video frames and audio blocks, we don’t look at any other data.

**Comment by Krakean** [comment]
@flibitijibibo Oh, I see. Is it possible to add support for subtitle stream in some near future to Theorafile? At least, if SRT file is found within container. 
And, as assumption, feed subscribed listener a text line that need to be rendered within given time stamps? So user with loaded font can render this text line over video frame

**Comment by flibitijibibo** [comment]
Someone else will have to write it, we don’t see subtitles in XNA videos so we have zero use cases for it.

**Comment by flibitijibibo** [comment]
Closing due to old age
